name: Run Lighthouse check.
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lighthouse check.
        uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: './.github/lighthouserc.json'
          uploadArtifacts: true
